// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/patyhank/ptd/app/ent/message"
	"github.com/patyhank/ptd/app/ent/postinfo"
	"github.com/patyhank/ptd/app/ent/predicate"
)

// PostInfoQuery is the builder for querying PostInfo entities.
type PostInfoQuery struct {
	config
	ctx          *QueryContext
	order        []postinfo.OrderOption
	inters       []Interceptor
	predicates   []predicate.PostInfo
	withMessages *MessageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PostInfoQuery builder.
func (piq *PostInfoQuery) Where(ps ...predicate.PostInfo) *PostInfoQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *PostInfoQuery) Limit(limit int) *PostInfoQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *PostInfoQuery) Offset(offset int) *PostInfoQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *PostInfoQuery) Unique(unique bool) *PostInfoQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *PostInfoQuery) Order(o ...postinfo.OrderOption) *PostInfoQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QueryMessages chains the current query on the "messages" edge.
func (piq *PostInfoQuery) QueryMessages() *MessageQuery {
	query := (&MessageClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(postinfo.Table, postinfo.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, postinfo.MessagesTable, postinfo.MessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PostInfo entity from the query.
// Returns a *NotFoundError when no PostInfo was found.
func (piq *PostInfoQuery) First(ctx context.Context) (*PostInfo, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{postinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *PostInfoQuery) FirstX(ctx context.Context) *PostInfo {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PostInfo ID from the query.
// Returns a *NotFoundError when no PostInfo ID was found.
func (piq *PostInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{postinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *PostInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PostInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PostInfo entity is found.
// Returns a *NotFoundError when no PostInfo entities are found.
func (piq *PostInfoQuery) Only(ctx context.Context) (*PostInfo, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{postinfo.Label}
	default:
		return nil, &NotSingularError{postinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *PostInfoQuery) OnlyX(ctx context.Context) *PostInfo {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PostInfo ID in the query.
// Returns a *NotSingularError when more than one PostInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *PostInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{postinfo.Label}
	default:
		err = &NotSingularError{postinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *PostInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PostInfos.
func (piq *PostInfoQuery) All(ctx context.Context) ([]*PostInfo, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryAll)
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PostInfo, *PostInfoQuery]()
	return withInterceptors[[]*PostInfo](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *PostInfoQuery) AllX(ctx context.Context) []*PostInfo {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PostInfo IDs.
func (piq *PostInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryIDs)
	if err = piq.Select(postinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *PostInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *PostInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryCount)
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*PostInfoQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *PostInfoQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *PostInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryExist)
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *PostInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PostInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *PostInfoQuery) Clone() *PostInfoQuery {
	if piq == nil {
		return nil
	}
	return &PostInfoQuery{
		config:       piq.config,
		ctx:          piq.ctx.Clone(),
		order:        append([]postinfo.OrderOption{}, piq.order...),
		inters:       append([]Interceptor{}, piq.inters...),
		predicates:   append([]predicate.PostInfo{}, piq.predicates...),
		withMessages: piq.withMessages.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithMessages tells the query-builder to eager-load the nodes that are connected to
// the "messages" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *PostInfoQuery) WithMessages(opts ...func(*MessageQuery)) *PostInfoQuery {
	query := (&MessageClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withMessages = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PostInfo.Query().
//		GroupBy(postinfo.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *PostInfoQuery) GroupBy(field string, fields ...string) *PostInfoGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PostInfoGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = postinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.PostInfo.Query().
//		Select(postinfo.FieldTitle).
//		Scan(ctx, &v)
func (piq *PostInfoQuery) Select(fields ...string) *PostInfoSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &PostInfoSelect{PostInfoQuery: piq}
	sbuild.label = postinfo.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PostInfoSelect configured with the given aggregations.
func (piq *PostInfoQuery) Aggregate(fns ...AggregateFunc) *PostInfoSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *PostInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !postinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *PostInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PostInfo, error) {
	var (
		nodes       = []*PostInfo{}
		_spec       = piq.querySpec()
		loadedTypes = [1]bool{
			piq.withMessages != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PostInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PostInfo{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withMessages; query != nil {
		if err := piq.loadMessages(ctx, query, nodes,
			func(n *PostInfo) { n.Edges.Messages = []*Message{} },
			func(n *PostInfo, e *Message) { n.Edges.Messages = append(n.Edges.Messages, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *PostInfoQuery) loadMessages(ctx context.Context, query *MessageQuery, nodes []*PostInfo, init func(*PostInfo), assign func(*PostInfo, *Message)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PostInfo)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Message(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(postinfo.MessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.post_info_messages
		if fk == nil {
			return fmt.Errorf(`foreign-key "post_info_messages" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "post_info_messages" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (piq *PostInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *PostInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(postinfo.Table, postinfo.Columns, sqlgraph.NewFieldSpec(postinfo.FieldID, field.TypeInt))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postinfo.FieldID)
		for i := range fields {
			if fields[i] != postinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *PostInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(postinfo.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = postinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PostInfoGroupBy is the group-by builder for PostInfo entities.
type PostInfoGroupBy struct {
	selector
	build *PostInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *PostInfoGroupBy) Aggregate(fns ...AggregateFunc) *PostInfoGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *PostInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, ent.OpQueryGroupBy)
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostInfoQuery, *PostInfoGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *PostInfoGroupBy) sqlScan(ctx context.Context, root *PostInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PostInfoSelect is the builder for selecting fields of PostInfo entities.
type PostInfoSelect struct {
	*PostInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *PostInfoSelect) Aggregate(fns ...AggregateFunc) *PostInfoSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *PostInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, ent.OpQuerySelect)
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostInfoQuery, *PostInfoSelect](ctx, pis.PostInfoQuery, pis, pis.inters, v)
}

func (pis *PostInfoSelect) sqlScan(ctx context.Context, root *PostInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
