// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/patyhank/ptd/app/ent/postinfo"
	"github.com/patyhank/ptd/app/ent/predicate"
)

// PostInfoDelete is the builder for deleting a PostInfo entity.
type PostInfoDelete struct {
	config
	hooks    []Hook
	mutation *PostInfoMutation
}

// Where appends a list predicates to the PostInfoDelete builder.
func (pid *PostInfoDelete) Where(ps ...predicate.PostInfo) *PostInfoDelete {
	pid.mutation.Where(ps...)
	return pid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pid *PostInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pid.sqlExec, pid.mutation, pid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pid *PostInfoDelete) ExecX(ctx context.Context) int {
	n, err := pid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pid *PostInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(postinfo.Table, sqlgraph.NewFieldSpec(postinfo.FieldID, field.TypeInt))
	if ps := pid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pid.mutation.done = true
	return affected, err
}

// PostInfoDeleteOne is the builder for deleting a single PostInfo entity.
type PostInfoDeleteOne struct {
	pid *PostInfoDelete
}

// Where appends a list predicates to the PostInfoDelete builder.
func (pido *PostInfoDeleteOne) Where(ps ...predicate.PostInfo) *PostInfoDeleteOne {
	pido.pid.mutation.Where(ps...)
	return pido
}

// Exec executes the deletion query.
func (pido *PostInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := pido.pid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{postinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pido *PostInfoDeleteOne) ExecX(ctx context.Context) {
	if err := pido.Exec(ctx); err != nil {
		panic(err)
	}
}
