// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthorsColumns holds the columns for the "authors" table.
	AuthorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "author_id", Type: field.TypeString, Unique: true},
		{Name: "last_seen", Type: field.TypeTime},
	}
	// AuthorsTable holds the schema information for the "authors" table.
	AuthorsTable = &schema.Table{
		Name:       "authors",
		Columns:    AuthorsColumns,
		PrimaryKey: []*schema.Column{AuthorsColumns[0]},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "raw_content", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "message_id", Type: field.TypeUint64, Default: 0},
		{Name: "message_author", Type: field.TypeInt},
		{Name: "post_info_messages", Type: field.TypeInt},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_authors_author",
				Columns:    []*schema.Column{MessagesColumns[6]},
				RefColumns: []*schema.Column{AuthorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "messages_post_infos_messages",
				Columns:    []*schema.Column{MessagesColumns[7]},
				RefColumns: []*schema.Column{PostInfosColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PostInfosColumns holds the columns for the "post_infos" table.
	PostInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "last_updated", Type: field.TypeTime},
		{Name: "current_viewing", Type: field.TypeBool, Default: true},
		{Name: "search_keywords", Type: field.TypeJSON, Nullable: true},
		{Name: "force_view_expire", Type: field.TypeTime, Nullable: true},
		{Name: "should_archived", Type: field.TypeBool, Default: false},
		{Name: "aid", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "post_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content_messages", Type: field.TypeJSON, Nullable: true},
		{Name: "channel_id", Type: field.TypeUint64, Default: 0},
	}
	// PostInfosTable holds the schema information for the "post_infos" table.
	PostInfosTable = &schema.Table{
		Name:       "post_infos",
		Columns:    PostInfosColumns,
		PrimaryKey: []*schema.Column{PostInfosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthorsTable,
		MessagesTable,
		PostInfosTable,
	}
)

func init() {
	MessagesTable.ForeignKeys[0].RefTable = AuthorsTable
	MessagesTable.ForeignKeys[1].RefTable = PostInfosTable
}
