// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Author is the predicate function for author builders.
type Author func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// PostInfo is the predicate function for postinfo builders.
type PostInfo func(*sql.Selector)
